
version: '2'
services:
##########ELK Stack##############
  es:
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - 9300
      - "30200:9200"

  logstash:
    image: logstash
    container_name: logstash
    command: logstash --verbose -e "input { beats {codec=>'json' port=>8092}} output {elasticsearch {hosts =>'es:9200' codec=>'json'} }"
    ports:
      - "8092:8092"
    links:
      - es

  kibana:
    image: kibana
    container_name: kibana
    links:
      - es
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - "30500:5601"


#######Service Registry###########
  registry:
    image: amalgam8/a8-registry
    container_name: registry
    ports:
      - "31300:8080"
    environment:
      - A8_STORE=redis
      - A8_STORE_ADDRESS=redis:6379
    links:
      - redis


  controller:
    image: amalgam8/a8-controller
    container_name: controller
    ports:
      - "31200:8080"
    environment:
      - A8_LOG_LEVEL=info
      - A8_DATABASE_TYPE=redis
      - A8_DATABASE_HOST=redis://redis:6379
    links:
      - redis


#######Redis Backend###########
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "31400:6379"





  zipkin_storage:
    image: openzipkin/zipkin-mysql:1.13.0
    container_name: mysql
    ports:
      - 3306:3306

  zipkin:
    image: openzipkin/zipkin:1.13.0
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/tree/1.13.0/zipkin-server#environment-variables
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
    ports:
      - "9411:9411"
    depends_on:
      - zipkin_storage


  dependencies:
    image: openzipkin/zipkin-dependencies
    container_name: dependencies
    entrypoint: crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin_storage