## Amalgam8 editor
## 
## default topology:
## ------------------------------------
## Tenant Space <service>:<version>:<port> (as brought up)
##              
##          gateway:latest:32700 -> webui:v1:7000(sidecar on :6379) -> topologyservice:v1:7100
##
## ------------------------------------
## A8 Control Plane (expected)
##
##          controller:8080       registry:8080     logstash:8092
## 
## Tracing
##        zipkin:9442  elasticsearch-zipkin:9300 
## 
##
##
version: '2'

services:


  gateway:
    image: amalgam8/a8-sidecar:alpine
    container_name: a8editor_gateway
    env_file: a8editor.env
    environment:
      - A8_SERVICE=gateway
      - A8_REGISTER=false
    ports:
      - "32700:6379"
    external_links:
      - logstash
      - controller
      - registry

  webui:
    image: faxg/a8editor-webui:v1
    env_file: a8editor.env
    environment:
      - A8_SERVICE=webui:v1
    external_links:
      - logstash
      - controller
      - registry
    ports:
      - "7000:3000"
      - "6379:6379"
    container_name: webui


  topologyservice:
    image: faxg/a8editor-topologyservice:v1
    env_file: a8editor.env
    environment:
      - A8_SERVICE=topologyservice:v1
    external_links:
      - logstash
      - controller
      - registry
    ports:
      - "7100:3100"
    container_name: topologyservice